Web_Final/Web_Final/Models/Process/Factory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Web_Final.Models.Process
{
    [Table("T1_Factory")]
    public class Factory
	{
		public int Id { get; set; }
		public string Code { get; set; } //공장코드
		public string Name { get; set; } //공장이름

        public string Constructor { get; set; } //
        public DateTime RegDate { get; set; }
        public string? Modifier { get; set; }
        public DateTime? ModDate { get; set; }

    }
}

Web_Final/Web_Final/Controllers/FactoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System.Collections;
using Web_Final.Repositories;
using Web_Final.Models;

namespace Web_Final.Controllers
{
    public class FactoryController : Controller
    {
        //repo
        private readonly IFactoryRepository factoryRepository;
        //컨트롤러 생성자
        public FactoryController(IFactoryRepository _factoryRepository)
        {
            factoryRepository = _factoryRepository;
        }
        //홈화면
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult userinfo()
        {
            return View();
        }
        //로그인
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ActionName("Login")]
        public async Task<IActionResult> GoLogin(string userid, string userpw) 
        {
            var user = await factoryRepository.Login(userid, userpw);
            if(user != null) 
            {
                HttpContext.Session.SetInt32("userid", (int)user.Id); // 로그인한 유저 uid 세션에 저장 (이거로 수정 삭제)
                HttpContext.Session.SetString("department", user.DepartmentCode);// 부서코드 (메뉴출력 다르게 할때 써먹음)
                HttpContext.Session.SetInt32("authority", user.Authority); //경영지원부 아이디로 로그인 할 경우, 아이디생성 권한(0일경우 가능)
                HttpContext.Session.SetString("username", user.Name); // 로그인한 사원정보 볼 수 있게
            }
                return View("userinfo", user);
        }


        //로그아웃
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("userid");
            HttpContext.Session.Remove("department");
            HttpContext.Session.Remove("authority");
            HttpContext.Session.Remove("username");
            return View("Logout");
        }
        //비밀번호 변경(사원이 직접변경)
        public IActionResult UpdatePw()
        {
            return View();
        }
        //비밀번호 변경 메소드
        [HttpPost]
        [ActionName("UpdatePw")]
        public async Task<IActionResult> Update(string pw)
        {
            int? uid = HttpContext.Session.GetInt32("userid");
            var result = await factoryRepository.UpdatePw(uid,pw);
            return View("index");
        }

        //계정 생성(경영)
        public IActionResult Create(string p_name, string p_department, string p_position, string p_id, string p_pw)
        {
            return View();
        }
        [HttpPost]
        [ActionName("Create")]
        public async Task<IActionResult> CreateId(string p_name, string p_department, string p_position, string p_id, string p_pw)
        {
            var new_user = await factoryRepository.Create(p_name, p_department, p_position, p_id, p_pw);
            return View("Index");
        }


        //사원정보 수정페이지
        public  IActionResult UpdateEmp()
        {
            return View();
        }
        [HttpPost]
        [ActionName("UpdateEmp")]
        public async Task<IActionResult> Update_test(string p_code,string p_department)
        {
			var user = await factoryRepository.Update(p_code, p_department);
            return View("index");
		}
    

        //존재하는 사원코드인지 검사
        public async Task<IActionResult> Check(string p_code) //실제 유저가 사용하는 id값을 입력받아야 돼
        {
            var user = await factoryRepository.FindId(p_code);
            if (user == null) return Json("none");
            else 
                return Json("exist");
        }
        
       
        public IActionResult Reset()
        {
            return View();
        }
        //비밀번호 0000초기화
        [HttpPost]
        [ActionName("Reset")]
        public async Task<IActionResult> ResetPw(string p_code) //비밀번호 초기화, p_code : 사원ID
        {
          var user = await factoryRepository.ResetPw(p_code);
            return View();
        }

        //사원ID 삭제 페이지       
        public IActionResult DeleteEmp()
        {
            return View();
        }
        //사원ID 삭제 (경영지원팀)
        [HttpPost]
        [ActionName("DeleteEmp")]
        public async Task<IActionResult> Delete(string p_code)
        {
            var user = await factoryRepository.Delete(p_code);
            return View();
        }

        //==========================================================================
        //테이블 조회 및 차트

        //사원 조회(경영)
        public async Task<IActionResult> EmployeesList()
		    {
			    var list = await factoryRepository.List(); //사원목록
			    return View(list);
		    }
		//창고자재 목록 (구매팀,생산팀)
		public async Task<IActionResult> StockList()
        {
            var list = await factoryRepository.Total_List();
            return View(list);
        }
        //입고내역 (구매팀)
        public async Task<IActionResult> InBoundList()
        {
            var list = await factoryRepository.InBoundList();
            return View(list);
        }
        //출고내역 (구매팀)
        public async Task<IActionResult> OutBoundList()
        {
			var list = await factoryRepository.OutBoundList();

			return View(list);
        }

        public async Task<IActionResult> InBoundList2()
        {
            var list = await factoryRepository.OutBoundList();

            return View(list);
        }
        //차트 (테이블)
        public async Task<IActionResult> Total_Chart()
        {
            var res = await factoryRepository.GetCountAsync();
            return View(res);
        }
        public async Task<IActionResult> CountJson()
        {
            return Json(await factoryRepository.GetCountAsync());
        }

    }
}

Web_Final/Web_Final/Views/Factory/Create.cshtml
@*
	경영지원부 >> 계정 생성
*@
@{
}
@*
*@
<!DOCTYPE html>
<html>

<head>
    <title>Registration Form</title>
    <!-- Add your CSS and JS files here (e.g., Bootstrap, jQuery) -->
</head>

<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="section-block" id="basicform">
                    <h3 class="section-title">회원가입</h3>
                    <p>업무시 사용할 아이디를 등록합니다.</p>
                </div>
                <div class="card">
                    <h5 class="card-header">Register</h5>
                    <div class="card-body">
                        <form method="post" action="/Factory/Create" id="create">
                            <div class="form-group">
                                <label for="username" class="col-form-label">사원 이름</label>
                                <input type="text" class="form-control" name="p_name" placeholder="Name" id="username" />
                                <div id="msg-name">
                                    @*안내메시지*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="dept">부서명</label>
                                <select name="p_department" class="form-control" id="dept">
                                    <option value="none">부서를 선택하세요</option>
                                    <option value="001">경영지원팀</option>
                                    <option value="002">구매팀</option>
                                    <option value="003">생산팀</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="position" class="col-form-label">직급</label>
                                <select name="p_position" class="form-control" id="position">
                                    <option value="none">직급을 선택하세요</option>
                                    <option value="인턴">인턴</option>
                                    <option value="사원">사원</option>
                                    <option value="대리">대리</option>
                                    <option value="과장">과장</option>
                                    <option value="부장">부장</option>
                                    <option value="사장">사장</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="userid" class="col-form-label">아이디</label>
                                <input type="text" class="form-control" name="p_id" placeholder="ID" id="userid" />
                                <div id="msg-id">
                                    @*안내메시지*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" for="pw">비밀번호</label>
                                <input type="password" class="form-control" name="p_pw" placeholder="Password" id="pw" />
                                <div id="msg-pw">
                                    @*안내메시지*@
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="pw2" class="col-form-label">비밀번호 확인</label>
                                <input type="password" class="form-control" id="pw2" placeholder="Password check" />
                                <div id="msg-pw2">
                                    @*안내메시지*@
                                </div>
                            </div>
                            <div style="margin-right:auto; margin-left:auto;">
                                <button type="button" id="btn_create" class="btn-primary btn-block" style="height:50px;">등록하기</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Add your JS files here (e.g., Bootstrap, jQuery) -->

</body>

</html>

	<script src="~/js/script.js"></script>
	<script src="~/js/input_check.js"></script>

Web_Final/Web_Final/Views/Factory/DeleteEmp.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link rel="stylesheet" type="text/css" href="~/css/manage.css" />




<div class="container mt-5">
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="section-block" id="basicform">
                <h3 class="section-title">ID삭제</h3>
                <p>사원의 아이디를 삭제 합니다</p>
            </div>
            <div class="card">
                <h5 class="card-header">Delete</h5>
                <div class="card-body">
                    <form method="post" action="/Factory/DeleteEmp" id="delete">
                        <input type="text" id="code" name="p_code" class="form-control" placeholder="사원ID 입력" style="margin-bottom: 0;" />
                        <br />

                        <button type="button" class="btn btn-danger" id="btn_delete">삭제하기</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/js/script.js"></script>

Web_Final/Web_Final/Views/Factory/EmployeesList.cshtml
@model List<Web_Final.Models.Account.Account>
@*
	경영 지원부 >> 사원목록 조회
*@
@{
	int row_count = 1; // 짝수줄 홀수 줄 마다 디자인 다름 
	string dept = "";
}


<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
	<div class="card">
		<h5 class="card-header">사원목록</h5>
		<div class="card-body">
			<div class="table-responsive">
				<div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4">
					<div class="row">
						<div class="col-sm-12 col-md-6">

						</div>
						<div class="col-sm-12 col-md-6">
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-striped table-bordered first dataTable" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
								<thead>
									<tr role="row">
										<th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 63.6406px; font-weight:bold">이름</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 50.9844px; font-weight:bold">부서</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 50.9844px; font-weight:bold">직급</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 97.25px; font-weight:bold">아이디</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 25.7344px; font-weight:bold">입사날짜</th>
								</thead>
								<tbody>

									
										
										@foreach (var data in Model)
										{
											<tr role="row" class="@(row_count % 2 == 1 ? "odd" : "even")">
												<td class="sorting_1">@(data.Name)</td>
											<td class="sorting_1">
												@switch (data.DepartmentCode)
												{
													case "001":
														dept = "경영지원팀";
														break;
														case "002":
														dept = "구매팀";
														break;
														case "003":
														dept = "생산팀";
														break;
												}
												@dept
											</td>

											<td class="sorting_1">@(data.Position)</td>
												<td class="sorting_1">@(data.UserId)</td>
												<td class="sorting_1">@(data.RegDate)</td>
											</tr>
												
											row_count++;
										}

										

						
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Web_Final/Web_Final/Views/Factory/InBoundList.cshtml
@*
	입고내역
	pk(입고번호) 부품명 수량 거래처 입고날짜 담당자

*@
@model List<Web_Final.Models.WareHouse.InBound>
@{
	int row_count = 1;
}
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
	<div class="card">
		<h5 class="card-header">입고내역</h5>
		<div class="card-body">
			<div class="table-responsive">
				<div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4">
					<div class="row">
						<div class="col-sm-12 col-md-6">
						</div>
						<div class="col-sm-12 col-md-6">
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-striped table-bordered first dataTable" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
								<thead>
									<tr role="row">
										<th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 63.6406px; font-weight:bold">입고번호</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 50.9844px; font-weight:bold">부품종류</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 50.9844px; font-weight:bold">수량</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 97.25px; font-weight:bold">거래처</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 25.7344px; font-weight:bold">입고날짜</th>
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 25.7344px; font-weight:bold">담당자</th>
								</thead>
								<tbody>



									@foreach (var data in Model)
									{
										<tr role="row" class="@(row_count % 2 == 1 ? "odd" : "even")">
											<td class="sorting_1">@(data.Id)</td>
											<td class="sorting_1">@(data.Product)</td>
											<td class="sorting_1">@(data.Amount)</td>
											<td class="sorting_1">@(data.Vendor)</td>
											<td class="sorting_1">@(data.RegDate)</td>
											<td class="sorting_1">@(data.Contact)</td>
										</tr>

										row_count++;
									}




								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Web_Final/Web_Final/Views/Factory/Index.cshtml
@*부서코드 001:경영지원, 002:구매팀, 003:생산팀*@

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    //세션에서 가져올 값 : 이름,부서코드(departmentCode),권한,uid
    string? name = HttpContextAccessor.HttpContext.Session.GetString("username"); //이름
    string? departmentCode = HttpContextAccessor.HttpContext.Session.GetString("department"); //부서
}

<link rel="stylesheet" type="text/css" href="~/css/index.css" />


@if(departmentCode == "001")
{
    <h1>경영 지원팀<br> @(name)님 안녕하세요!!</h1>
    <hr />
    <div class="menubox" style="margin-top:200px;">
        <div id="selectbox" class="top">
        <a href="create" class="img-box">
            <img src="~/assets/images/Account/Adduser.png">
            <h3 class="menu">사원추가</h3>
        </a>
        </div>

        <div id="selectbox" class="top">
            <a href="updateEmp" class="img-box">
            <img src="~/assets/images/Account/UpdateUser.png">
                <h3 class="menu">부서이동</h3>
        </a>
        </div>

        <div id="selectbox" class="top">
            <a href="deleteEmp" class="img-box">
            <img src="~/assets/images/Account/DeleteUser.png">
                <h3 class="menu">사원 삭제</h3>
        </a>
        </div>

        <div id="selectbox" class="bottom">
            <a href="EmployeesList" class="img-box">
            <img src="~/assets/images/Account/UserList.png">
                <h3 class="menu">사원목록</h3>
        </a>
        </div>

        <div id="selectbox" class="bottom">
            <a href="Reset" class="img-box">
            <img src="~/assets/images/Account/ResetUser.png">
                <h3 class="menu">비밀번호 초기화</h3>
        </a>
        </div>

    </div>
}
else if(departmentCode == "002")
{
    <h1>구매팀<br> @(name)님 안녕하세요!!</h1>
    <hr />
    <div class="menubox" style="margin-top:200px;">
        <div id="selectbox" class="top">
            <a href="stockList" class="img-box">
                <img src="~/assets/images/stock_list.png">
                <h3 class="menu">재고조회</h3>
            </a>
        </div>

        <div id="selectbox" class="top">
            <a href="inboundList" class="img-box">
                <img src="~/assets/images/inbound_list.png">
                <h3 class="menu">입고내역</h3>
            </a>
        </div>

        <div id="selectbox" class="top">
            <a href="outBoundList" class="img-box">
                <img src="~/assets/images/outbound_list.png">
                <h3 class="menu">출고내역</h3>
            </a>
        </div>


    </div>
}

else if(departmentCode == "003")
{
    <h1>생산팀<br> @(name)님 안녕하세요!!</h1>
    <hr />
    <div class="menubox" style="margin-top:200px;">
        <div id="selectbox" class="top">
            <a href="stockList" class="img-box">
                <img src="~/assets/images/stock_list.png">
                <h3 class="menu">재고조회</h3>
            </a>
        </div>

        <div id="selectbox" class="top">
            <a href="inboundList2" class="img-box">
                <img src="~/assets/images/inbound_list.png">
                <h3 class="menu">입고내역</h3>
            </a>
        </div>

        <div id="selectbox" class="top">
            <a href="Total_Chart" class="img-box">
                <img src="~/assets/images/Chart.png">
                <h3 class="menu">완제품 생산현황</h3>
            </a>
        </div>


    </div>
}   
else{
    <script>
    alert("잘못된 로그인 정보 입니다!");
        location.href = "@Url.Action("Login","Factory")";
    </script>

}
    

Web_Final/Web_Final/Views/Factory/Login.cshtml
@*
    로그인
*@
@{
    Layout = null;
}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../assets/vendor/bootstrap/css/bootstrap.min.css">
    <link href="../assets/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link rel="stylesheet" href="../assets/libs/css/style.css">
    <link rel="stylesheet" href="../assets/vendor/fonts/fontawesome/css/fontawesome-all.css">
    <style>
       
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
        }

       
        .splash-container {
            max-width: 400px; /* 원하는 폼 너비로 조절하세요 */
            margin: auto;
        }

        .card {
            border: none;
            box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
        }

        .card-header {
            background-color: #f8f9fa; /* 카드 헤더의 배경색 설정 */
            border-bottom: none;
            padding-bottom: 0;
        }

        .logo-img {
            width: 350px; /* 원하는 로고 이미지의 크기로 조절하세요 */
            height: 150px;
        }

        .form-control-lg {
            padding: 20px; /* 원하는 폼 컨트롤의 패딩을 조절하세요 */
            font-size: 18px; /* 원하는 폰트 크기로 조절하세요 */
        }

        .btn-primary {
            font-size: 20px; /* 원하는 버튼 폰트 크기로 조절하세요 */
            padding: 15px; /* 원하는 버튼의 패딩을 조절하세요 */
        }
    </style>

</head>

<body>
    <!-- ============================================================== -->
    <!-- login page  -->
    <!-- ============================================================== -->
    <div class="splash-container">
        <div class="card ">
            <div class="card-header text-center"><img class="logo-img" src="~/assets/images/logo3.png"  alt="logo"><span class="splash-description"></span></div>
            <div class="card-body">
                <form method="post" action="/Factory/Login" name="login" id="login">
                    <div class="form-group">
                        <input class="form-control form-control-lg" name ="userid" id="userid" type="text" placeholder="아이디" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control form-control-lg" id="pw" type="password" placeholder="패스워드" name="userpw">
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg btn-block">로그인</button>
                </form>
            </div>
        </div>
    </div>

    <!-- ============================================================== -->
    <!-- end login page  -->
    <!-- ============================================================== -->
    <!-- Optional JavaScript -->
    <script src="../assets/vendor/jquery/jquery-3.3.1.min.js"></script>
    <script src="../assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
</body>

</html>

<script src="~/js/script.js"></script>

Web_Final/Web_Final/Views/Factory/Logout.cshtml
@*
	로그아웃
*@
@{
	Layout = null;
}

<script>
	alert("로그아웃 되었습니다.");
	location.href = "@Url.Action("Login","Factory")";
</script>

Web_Final/Web_Final/Views/Factory/OutBoundList.cshtml
@*
   Outbound
pk(출고번호) 부품명 수량 담당자 출고날짜
*@
@model List<Web_Final.Models.WareHouse.OutBound>
@{
	int row_count = 1;
}
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
	<div class="card">
		<h5 class="card-header">출고내역</h5>
		<div class="card-body">
			<div class="table-responsive">
				<div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4">
					<div class="row">
						<div class="col-sm-12 col-md-6">
						</div>
						<div class="col-sm-12 col-md-6">
						</div>
					</div>
					<div class="row">
						<div class="col-sm-12">
							<table class="table table-striped table-bordered first dataTable" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
								<thead>
									<tr role="row">
								@*pk*@		<th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 63.6406px; font-weight:bold">출고번호</th>
										@*부품명*@
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 50.9844px; font-weight:bold">이름</th>
										@*수량*@
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 50.9844px; font-weight:bold">수량</th>
										@*담당자*@
										<th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 97.25px; font-weight:bold">담장자</th>
										@*출고날짜*@
										<th class="sorting " tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 25.7344px; font-weight:bold">출고날짜</th>
								</thead>
								<tbody>
									@foreach (var data in Model)
									{
										<tr role="row" class="@(row_count % 2 == 1 ? "odd" : "even")">
											<td class="sorting_1">@(data.Id)</td> @*pk*@
											<td class="sorting_1">@(data.Product)</td> @*부품명*@
											<td class="sorting_1">@(data.Amount)</td> @*수량*@
											<td class="sorting_1">@(data.Contact)</td> @*담당자*@
											<td class="sorting_1">@(data.RegDate)</td> @*출고 날짜*@
										</tr>
										row_count++;
									}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Web_Final/Web_Final/Views/Factory/Reset.cshtml
@*
  사원정보 리셋
*@
@{
}
<link rel="stylesheet" type="text/css" href="~/css/manage.css" />


<div class="container mt-5">
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="section-block" id="basicform">
                <h3 class="section-title">비밀번호 초기화</h3>
                <p>사원의 비밀번호를 초기화 합니다</p>
            </div>
            <div class="card">
                <h5 class="card-header">ResetPw</h5>
                <div class="card-body">
                    <form method="post" action="/Factory/Reset" name="reset" id="reset">
                        <input type="text" id="code" name="p_code" class="form-control" placeholder="사원ID 입력" style="margin-bottom: 0;" /><br />
                        <button type="button" class="btn btn-outline-danger" id="btn_reset">초기화</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/js/script.js"></script>

Web_Final/Web_Final/Views/Factory/Total_Chart.cshtml
@model List<Web_Final.Models.Process.ItemCount>
@*
   차트 : 생산
*@
@{
}

<div class="container-fluid">
    <h1 class="display-4">완제품 생산 현황</h1>
    <table class="table table-hover">
        <thead class="table-success">
            <tr>
                <th>제품명</th>
                <th>제품 코드</th>
                <th>총 생산수량</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Code</td>
                    <td>@item.Count</td>
                </tr>
                }
                    
        </tbody>
    </table>
    @*chart가 그려질 canvas*@
    <div>
        <canvas id="chart"></canvas>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</div>

<script src="~/js/chart.js"></script>

Web_Final/Web_Final/Views/Factory/userinfo.cshtml
@model Web_Final.Models.Account.Account
@*
    로그인
*@
@if (Model == null)
{
    <script>
        alert("회원정보가 일치하지 않거나 존재하지 않는 ID입니다.");
        location.href = history.back();
    </script>
}
else{
    <script>
        alert("로그인 되었습니다.");
        location.href = "index";
    </script>

}